target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'Nuke', :git => 'https://github.com/kean/Nuke', :branch => 'master'
  
#   pod 'MultiPlatformLibrary', :path => '../shared'
#   pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.11.0'
  # pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.8.1'
#   pod 'MultiPlatformLibraryMvvm', :path => '../../'
end
